# FROM alpine:latest

# COPY create_db.sql create_db.sql
# COPY docker-entrypoint.sh docker-entrypoint.sh

# RUN chmod 777 docker-entrypoint.sh  # to avoid '/bin/sh: ./docker-entrypoint.sh: Permission denied'

# ENTRYPOINT './docker-entrypoint.sh'
